function love.conf(c)
  c.title = "Projet tutoré"     -- The title of the window the game is in (string)
  c.author = ""                 -- The author of the game (string)
  c.url = nil                   -- The website of the game (string)
  c.identity = nil              -- The name of the save directory (string)
  c.version = "0.8.0"           -- The LÖVE version this game was made for (string)
  c.console = false             -- Attach a console (boolean, Windows only)
  c.release = false             -- Enable release mode (boolean)
  c.screen.width = 800          -- Largeur de la fenêtre (number)
  c.screen.height = 600         -- Hauteur de la fenêtre (number)
  c.screen.swidth = 400         -- Largeur de la zone de jeu (number)
  c.screen.sheight = 300        -- Hauteur de la zone de jeu (number)
  c.screen.fullscreen = false   -- Enable fullscreen (boolean)
  c.screen.vsync = true         -- Enable vertical sync (boolean)
  c.screen.fsaa = 0             -- The number of FSAA-buffers (number)
  c.modules.joystick = true     -- Enable the joystick module (boolean)
  c.modules.audio = true        -- Enable the audio module (boolean)
  c.modules.keyboard = true     -- Enable the keyboard module (boolean)
  c.modules.event = true        -- Enable the event module (boolean)
  c.modules.image = true        -- Enable the image module (boolean)
  c.modules.graphics = true     -- Enable the graphics module (boolean)
  c.modules.timer = true        -- Enable the timer module (boolean)
  c.modules.mouse = true        -- Enable the mouse module (boolean)
  c.modules.sound = true        -- Enable the sound module (boolean)
  c.modules.physics = true      -- Enable the physics module (boolean)
end